  name: Caverns-of-Amethyst
  main: com.geekazodium.cavernsofamethyst.Main
  api-version: 1.13
  version: 1.0-SNAPSHOT
  depend:
    - LibsDisguises
  commands:
    getItem:
      description: gives sender a custom item
      permission: operator
      permission-message: you do not have the permissions to use this command
    debugHitbox:
      description: shows hitboxes to players
      permission: operator
      permission-message: you do not have the permissions to use this command
    generateDungeon:
      description: command for testing dungeon generation
      permission: operator
      permission-message: you do not have the permissions to use this command
    resetCharacter:
      description: reset your adventure (used for testing only)
      permission: operator
      permission-message: you do not have the permissions to use this command
    setMaxHealth:
      description: set max health (used for testing only)
      permission: operator
      permission-message: you do not have the permissions to use this command
    skillMenu:
      description: open player attribute menu
    setSkin:
      description: sets your skin